### ISSUE TITLE
[meta] coredistools in jitutils

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/jitutils#290]
#289 will add support for building coredistools from dotnet/jitutils repo. This PR adds multiple scripts for enlisting and building LLVM components as well coredistools itself. At the end of the corresponding pipeline run, each job produces a coredistools library binary file (e.g. coredistools.dll, libcoredistools.dylib) for a specified host platform (e.g. windows-arm64). Such binaries files support all the target architectures, so, presumably, they can be used in cross-architecture scenarios (e.g. running superpmi replay with altjit on windows-x86 host targetting linux-arm with mch files collected on linux-arm).

This issue is to track the remaining work:
- [ ] Test all the binaries with SuperPMI for all platforms in the matrix:
  - [x] windows-x86 replay/collect with 260 framework libraries
  - [x] windows-x64 replay/collect with 260 framework libraries
  - [x] windows-arm (native) replay/collect with 260 framework libraries
  - [x] windows-arm (on windows-x86 host) replay with windows-arm *.mch and clrjit_win_arm_x86.dll
  - [ ] windows-arm64 (native)
  - [ ] windows-arm64 (on windows-x64 host)
  - [x] linux-x64
  - [x] linux-arm (native) blocked by https://github.com/dotnet/runtime/issues/42641
  - [ ] linux-arm64 (native)
  - [ ] linux-arm64 (on linux-x64 host)
  - [x]  *(Optional)* linux-x64 (on windows-x64 host)
  - [ ]  *(Optional)* windows-x64 (on linux-x64 host)
  - [ ]  *(Optional)* linux-arm (on windows-x86 host)
  - [ ]  *(Optional)* linux-arm64 (on windows-x64 host)
  - [ ]  *(Optional)* windows-arm64 (on linux-x64 host)
- [x] Test all the binaries with GCStress for the following platforms:
  - [x] windows-x86
  - [x] windows-x64
  - [x] linux-x64
- [x] Test all the binaries with R2RDump for the following host platforms:
  - [x] windows-x86
  - [x] windows-x64
  - [x] linux-x64
- [x] Fix issue on Arm32 by porting some of the changes in dotnet/llilc#1098. **Update:** fixed with https://github.com/dotnet/jitutils/pull/291
- [x] Fix issue on Arm64 and propose a solution to Arm64 literal pool issue as discussed in dotnet/llilc#1098 This should resolve https://github.com/dotnet/runtime/issues/10281
- [x] Automate publishing (i.e. add support for producing nuget packages and publishing them as pipeline artifacts). Note that publishing the nuget packages to a nuget repository is outside of the scope. It can accomplished after the repo will onboard onto Arcade - I partly finished this task in #219
- [x] Document the completed work for the future maintenance purposes
- [ ] *(Optional)* Update to LLVM 10.0.1 that is the current stable version of LLVM. At the moment, coredistools in that PR uses LLVM 9.0.1 and the update to higher version requires changing coredistools.cpp itself since there were some changes in LLVM API between 9 and 10.

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib 
Also cc @janvorli and @davidwrighton who might be interested in this work
